// examples/vue/src/App.vue
<script setup lang="ts">
import { onKeyDown } from "@vueuse/core";
import { openStore, store } from "./store";
import { exit } from "@tauri-apps/plugin-process";
import { clearAutosave, setAutosave } from "@tauri-store/vue/src/index.js";

const { start, stop, save, saveNow } = store.$tauri;

onKeyDown("Escape", () => void exit(0));
</script>

<template>
  <main>
    <div class="action">
      <button type="button" @click="() => setAutosave(5000)">Set Autosave</button>
      <button type="button" @click="clearAutosave">Clear Autosave</button>
    </div>
    <section id="counter">
      <p>Counter: {{ store.counter }}</p>
      <div class="action">
        <button type="button" @click="() => store.counter++">Increment</button>
        <button type="button" @click="start">Start</button>
        <button type="button" @click="stop">Stop</button>
        <button type="button" @click="save">Save</button>
        <button type="button" @click="saveNow">Save Now</button>
        <button type="button" @click="openStore">Open</button>
      </div>
    </section>
  </main>
</template>

// examples/zustand/src/App.tsx
/* eslint-disable @typescript-eslint/no-floating-promises */
/* eslint-disable @typescript-eslint/no-misused-promises */
import { useEffect } from "react";
import { exit } from "@tauri-apps/plugin-process";
import { openStore, tauriHandler, useCounterStore } from "./store";
import { clearAutosave, setAutosave } from "@tauri-store/zustand/src/index.js";

export default function App() {
  const counter = useCounterStore((state) => state.counter);
  const increment = useCounterStore((state) => state.increment);

  useEffect(() => {
    window.addEventListener("keydown", onKeyDown);
    return () => {
      window.removeEventListener("keydown", onKeyDown);
    };
  }, []);

  return (
    <main>
      <div className="action">
        <button type="button" onClick={() => setAutosave(5000)}>
          Set Autosave
        </button>
        <button type="button" onClick={clearAutosave}>
          Clear Autosave
        </button>
      </div>

      <section id="counter">
        <p>Counter: {counter}</p>
        <div className="action">
          <button type="button" onClick={increment}>
            Increment
          </button>
          <button type="button" onClick={() => tauriHandler.start()}>
            Start
          </button>
          <button type="button" onClick={() => tauriHandler.stop()}>
            Stop
          </button>
          <button type="button" onClick={() => tauriHandler.save()}>
            Save
          </button>
          <button type="button" onClick={() => tauriHandler.saveNow()}>
            Save Now
          </button>
          <button type="button" onClick={() => tauriHandler.destroy()}>
            Destroy
          </button>
          <button type="button" onClick={openStore}>
            Open
          </button>
        </div>
      </section>
    </main>
  );
}

function onKeyDown(e: KeyboardEvent) {
  if (e.key === "Escape") {
    e.preventDefault();
    exit(0);
  }
}
